### ISSUE TITLE
ofType does not work on generics of generics

### ISSUE THREAD

**Issue by tokou** [ReactiveX/RxKotlin#148]
This is probably due to type erasure but these tests fail whereas I was expecting them to pass.
When you look at the underlying implementation, it is understandable. But the problem is that the type inference works (it is expecting the correct types `Model<Elem<Int>>` and `Model<Elem<String>>` and not juste `Model<Elem<*>>`).

```
import io.reactivex.Flowable
import io.reactivex.rxkotlin.ofType
import org.junit.Test

class OfTypeKtTest {

    data class Elem<out R>(val content: R)
    data class Model<out T>(val elems: List<T>)

    @Test
    fun testString() {
        val item = Model(listOf(Elem("Hello")))
        val item2 = Model(listOf(Elem(12)))
        val flow = Flowable.just(item, item2)

        flow.ofType<Model<Elem<String>>>().test().assertResult(item)
    }

    @Test
    fun testInt() {
        val item = Model(listOf(Elem("Hello")))
        val item2 = Model(listOf(Elem(12)))
        val flow = Flowable.just(item, item2)

        flow.ofType<Model<Elem<Int>>>().test().assertResult(item2)
    }
}
```

**Comment by ajalt** [comment]
You're right that the problem is due to type erasure.

If you check the bytecode, you can see that `flow.ofType<List<Elem<Int>>>` is compiled to `float.ofType(List.class)`, since classes can't contain type parameters. 

There's no way to do an instance check on the value of generic type parameters are runtime, and unfortunately there's nothing that this library can do to help.

**Comment by thomasnield** [comment]
Thanks @ajalt
