### ISSUE TITLE
Call for a new leadership

### ISSUE THREAD

**Issue by MarioAriasC** [ReactiveX/RxKotlin#85]
Hi everyone,

As some of you know, I'm the original author of RxKotlin back in the days were neither Kotlin nor RxJava reached their 1.0 versions. (In fact RxKotlin wasn't independent from RxJava but part of the same repository)

That gave me a position as the natural leader of this project, for that I'm really grateful.

Shamefully my commitment and involvement to this project in the last months hasn't being the best due to my multiple occupations (Full time job, part time distance learning degree in Theology, other open-source projects and so on) and before hurting the community I prefer to move aside as a leader and remain only as contributor and speaker.

There are great members of this community that surely could do a better job than me at this very moment.

Is someone interested in this role?

Cheers

**Comment by stepango** [comment]
@MarioAriasC Thanks for this great library! I used it a lot in my last two projects. And even ported 90% of it to RxJava2 for current one. And yeah, I'm interested!

**Comment by thomasnield** [comment]
Thanks @MarioAriasC for bringing this library to where it's at today. My team and I use it daily. 

I'll stay at the end of the line in terms of leadership candidacy, and it sounds like others are interested already. I'm busy already maintaining [RxJavaFX](https://github.com/ReactiveX/RxJavaFX) and [RxKotlinFX](https://github.com/thomasnield/RxKotlinFX). I also have my full-time job and some O'Reilly projects. 

But I'll do my best to be an active and contribution member of the community, and can take stewardship if others become too busy.

**Comment by MarcinMoskala** [comment]
Also big thanks, @MarioAriasC I also use it in my project. But I also use lot's of own extensions and methods that makes RxJava nice and simple.

I fill that we can get more from Kotlin to improve RxJava. I have some features and vision how this could work. I think that there should be a develop branch to allow discussion and consultations before adding features to master. I don't have a lot of experience in Open Source but I am using Kotlin in production since Year and I ma writing book about it. 

Some examples of what I would like to add to this library. Of course we will start a discussion before and create test:

```
fun <T> Observable<T>.applySchedulers(): Observable<T> =
        subscribeOn(Schedulers.io())
        .unsubscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())

// It is waiting for Kotlin to allow default lambdas in inline functions. 
// When it will be inline then it will be much quicker and better 
// because of no need for creating lambda functions which are not really
// effective in Kotlin. They create new class for each new lambda method
fun <T> Observable<T>.smartSubscribe(
        onStart: (() -> Unit)? = null,
        onHttpError: (HttpErrorWithBody) -> Unit = { e -> logError(e) },
        onNetworkError: (Throwable) -> Unit = { logError(it) },
        onFinish: (() -> Unit)? = null,
        onSuccess: (T) -> Unit = {}): Subscription =
        addStartFinishActions(onStart, onFinish)
                .subscribe(onSuccess, { onErrorImpl(it, onHttpError, onNetworkError) })

fun <T> Observable<T>.addStartFinishActions(
        onStart: (() -> Unit)? = null, 
        onFinish: (() -> Unit)? = null
): Observable<T> {
    onStart?.invoke()
    return doOnTerminate({ onFinish?.invoke() })
}
```

**Comment by thomasnield** [comment]
@MarcinMoskala You can always contribute too, and you certainly don't need to own the repository to do that : ) I cast my vote for @stepango since we need someone who has done some open-source projects, and it looks like he's done the less fun work of porting to RxJava2. A good maintainer has a mind for stability in my opinion, and is willing to do the non-sexy work. The community can always put in pull requests with innovations, and he/she can push back or accept it in alignment with the project's vision.

**Comment by JakeWharton** [comment]
I am against all of those additions. I would even like to start a
discussion about removing items from this library.

**Comment by cy6erGn0m** [comment]
@MarioAriasC @thomasnield so, have you decided to transfer leadership finally?

**Comment by MarioAriasC** [comment]
@cy6erGn0m Are you interested? You did a lot of clean up and put the library in good shape early on.

The maintainer should be a person with proved experience on both, Kotlin an Open source development.

@JakeWharton agree. Maybe we should split the library in a core module and some utility modules with extras. We did have a discussion earlier but I didn't do any progress on that

**Comment by cy6erGn0m** [comment]
@MarioAriasC   I just wanted a leader that is more Rx-experienced than me. I can take it if you don't have better candidates with both Kotlin and Rx experience

**Comment by jacinpoz** [comment]
@MarioAriasC I use Kotlin and RxJava pretty much daily as part of my full time job, and I also would be happy to contribute, but I am 100% sure there are much better candidates out there with very good experience handling open source development.

**Comment by thomasnield** [comment]
Alright let's grant collaboration rights to someone. I think @stepango is a good fit for ownership. I'd step up and do it but I'm swamped until Spring next year. I can help.

**Comment by MarioAriasC** [comment]
What do you think @stepango ?

**Comment by stepango** [comment]
@MarioAriasC I'm in!

**Comment by jackmalpo** [comment]
What's the status on RxJava 2 implementation? Is anyone actively working on it yet?

**Comment by pabl0rg** [comment]
@MarioAriasC So, do we have a new project leader?  It would be great to use the Kotlin lib with RxJava 2

**Comment by pwittchen** [comment]
> @JakeWharton agree. Maybe we should split the library in a core module and some utility modules with extras. We did have a discussion earlier but I didn't do any progress on that

@MarioAriasC Please note, it's general purpose library, so it could be used in different projects. E.g. for web and desktop apps. It can be used not only Android and not only fo HTTP requests and with networking. I like the direction of RxAndroid where the library was simplified. Only stuff, which is commonly used remained there and rest of the utilities were removed. I agree with @JakeWharton and RxKotlin should go in the same direction. This library should be kept as simple as possible and additional features and utilities can be provided as external, totally independent libraries like for RxAndroid.

Moreover, I would keep RxKotlin dependent on RxJava1.x aside RxKotlin dependent on RxJava2.x (as a  separate module or a separate Git branch) like in original RxJava project, because people still use RxJava1.x and there are projects dependent on it, which hasn't been migrated to the newer version of RxJava yet.

P.S. It's kinda off-topic there, but such discussion is IMO important.

**Comment by MarioAriasC** [comment]
A few weeks ago I was speaking privately with @stepango and he accepts the leadership role over RxKotlin, Thank you

**Comment by thomasnield** [comment]
Excellent! Thanks @MarioAriasC. Hey @stepango, I will file some issues for some proposals. In the upcoming Packt Book _Learning RxJava_ I'm writing, I have a chapter dedicated to Kotlin, and I'd like to cover RxKotlin as a library in a 1.0/2.0 release state if that's possible. To get a 1.0 release out, I think the main task is to eliminate some of the API's and make it more minimalist...

**Comment by stepango** [comment]
@thomasnield totally agreed with you, first thing I'll focus is 1.0 release. Waiting for access rights to repo to make it happen.
